### ISSUE TITLE
SimpleItemEditor Bug

### ISSUE THREAD

**Issue by ivdsh1** [White-145/item-editor#6]
I think I found a small bug...
https://youtu.be/aUSaYmDpEdo

**Comment by White-145** [comment]
Hi! This is most likely happening because in 1.20.6 there are 2 types of item names: Item name and Custom name. Anvils are changing item's Custom name, and the same Custom name is used by name tags for renaming entities. `/edit name set` changes item's Item name, while you probably need to use `/edit name custom set`. Sorry if it's confusing

**Comment by ivdsh1** [comment]
Oh, I didn't know about this other command... (I hadn't even tested it...)
